"use client";
import { terms } from "@/DB/terms";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { LoginUserContext } from "@/context/LoginUserContext";
import { useRouter } from "next/navigation";
import React, { useContext } from "react";

const Terms = () => {
  const router = useRouter();
  const { loginUser } = useContext(LoginUserContext);
  if (!loginUser) {
    router.push("/");
    return;
  }
  return (
    <>
      <Header />
      <div className="flex justify-center">
        <div className="flex flex-col px-5 py-7 md:px-10 md:py-10 w-full md:w-4/5 items-center gap-8">
          <div className="text-2xl font-semibold ">TERMS & CONDITIONS</div>
          <div className="flex flex-col gap-3">
            <h2 className="text-base font-medium">
              This document is an electronic record in accordance with
              Information Technology Act, 2000 and rules there under as
              applicable and the provisions pertaining to electronic records in
              various statutes as amended by the Information Technology Act,
              2000 and other applicable laws. This electronic record is
              generated by a computer system and does not require any physical
              or digital signatures to make the terms of this policy binding.{" "}
            </h2>
            <h2 className="text-base font-medium text-gray-700">
              PLEASE READ THE TERMS AND CONDITIONS THOROUGHLY AND CAREFULLY.
            </h2>
            {terms.map((curr, index) => {
              return (
                <div key={index}>
                  <h2 className="text-xl font-medium">{curr.heading}</h2>
                  <h2 id="content" className="text-base font-normal">
                    {curr.content}
                  </h2>
                </div>
              );
            })}
            <div className="text-base">
              <div className="font-semibold text-lg">
                In no event will we be liable for any loss or damage including
                without limitation, indirect or consequential loss or damage, or
                any loss or damage whatsoever arising from loss of data or
                profits arising out of, or in connection with, the use of this
                website.
              </div>
              <div className="text-lg font-semibold py-2">
                General Information
              </div>
              <span className="font-semibold ">1. ENTIRE TERMS OF USE </span>
              The Terms of Use the Privacy Policy and any other legal notices or
              Additional Policies published by RodBez on the Website, shall
              constitute the entire agreement between you and RodBez concerning
              the Website. If any provision of the Terms of Use is deemed
              invalid by a court of competent jurisdiction, the invalidity of
              such provision shall not affect the validity of the remaining
              provisions of the Terms of Use, which shall remain in full force
              and effect. No waiver of any provision of these Terms of Use shall
              be deemed a further or continuing waiver of such term or any other
              term, and RodBez’s failure to assert any right or provision under
              these Terms of Use shall not constitute a waiver of such right or
              provision.
              <br />
              <br />
              <span className="font-semibold">2. STATUTE OF LIMITATIONS </span>
              You agree that any cause of action arising out of or related to
              the Website must commence within one (1) year after the cause of
              action accrues. Otherwise, such cause of action is permanently
              barred.
              <br />
              <br />
              <div className="text-lg font-semibold">
                These Terms of Use were most recently updated on December 6,
                2023.
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Terms;
