"use client";
import Footer from "@/components/Footer";
import React from "react";
const Privacy = () => {
  return (
    <>
      <div>
        <div className="flex justify-center">
          <div className="flex flex-col px-5 py-7 md:px-10 md:py-10 w-full md:w-4/5 items-center gap-8">
            <div className="text-2xl font-semibold ">Privacy Policy </div>
            <div className="flex flex-col gap-3">
              <h2 className="text-base font-medium">
                This document is an electronic record in accordance with
                Information Technology Act, 2000 and rules there under as
                applicable and the provisions pertaining to electronic records
                in various statutes as amended by the Information Technology
                Act, 2000 and other applicable laws. This electronic record is
                generated by a computer system and does not require any physical
                or digital signatures to make the terms of this policy binding.{" "}
              </h2>
              <div className="flex flex-col gap-2">
                <h2 className="text-xl font-medium">
                  1. Collection and Use of Sensitive Personal Data:
                </h2>
                <h2 className="text-base font-normal">
                  When you request services from us, operate a vehicle or
                  equipment with in-vehicle or in-equipment technology, access
                  our websites, utilize our mobile “apps” or otherwise interact
                  with us, for example, but without limitation, through our
                  official corporate pages on third party social networks (such
                  as Facebook) or the “apps” on those pages, you consent to our
                  collection, retention and use of your personal data in the
                  manner described in this policy In quest of quality
                  performance in services we collect other personal data such
                  as: Vehicle Use Data: To maintain and protect the Vehicle and
                  to prevent and detect crime the vehicle may be equipped with
                  devices which allow us to send commands to and receive certain
                  information from the vehicle to monitor the condition,
                  performance and operation of a Vehicle. This is also done as a
                  security and safety measure against accident or theft and to
                  provide you with valuable services and information. Location
                  Tracking: To avoid theft, or to track you in case of any
                  emergency, accident etc., we track the geolocation data of
                  your vehicle from Global Positioning System (GPS). CarLand
                  assure that we will not public your location or movement
                  unless it is required and necessary under personal, medical
                  and legal emergencies. Under the same circumstances we may
                  share the location of your vehicle with the police, insurance
                  companies, tribunals, courts or other law enforcement
                  agencies. Driver and vehicle information: By ordering or
                  registering and availing the services, you authorize us to
                  access your driver’s record, vehicle travelled history report
                  pertaining to your trip from all applicable entities and
                  authorities. You may withdraw your consent to collection and
                  use of your sensitive Sensitive Personal Data in future. You
                  may do so by unregistering from CarLand.
                </h2>
              </div>
              <div className="flex flex-col gap-2">
                <h2 className="text-xl font-medium">
                  2. Collection And Use Of Non Sensitive Personal Data:
                </h2>
                <h2 className="text-base font-normal">
                  We also collect data in a form that does not, on its own,
                  permit direct association with any specific individual. We may
                  collect, use, transfer, and disclose non-Sensitive Personal
                  Data for any purpose. The following are some examples of
                  non¬Sensitive Personal Data that we collect and how we may use
                  it:
                  <br />
                  1. We may collect information such as occupation, language,
                  zip code, area code, unique device identifier, referrer URL,
                  and location so that we can better understand customer
                  behavior and improve our products, services, and advertising.{" "}
                  <br />
                  2. This information is aggregated and used to help us provide
                  more useful information to our customers and to understand
                  which parts of our website, products, and services are of most
                  interest. Aggregated data is considered non¬Sensitive Personal
                  Data for the purposes of this Privacy Policy. <br />
                  3. We may collect and store details of how you use our
                  services, including search queries. This information may be
                  used to improve the relevancy of results provided by our
                  services. Except in limited instances to ensure quality of our
                  services over the Internet, such information will not be
                  associated with your IP address. <br />
                  4. With your explicit consent, we may collect data about how
                  you use your device and applications in order to help app
                  developers improve their apps.{" "}
                </h2>
              </div>
              <div className="flex flex-col gap-2">
                <h2 className="text-xl font-medium">
                  3. Protection of Sensitive Personal Data or Information:
                </h2>
                <h2 className="text-base font-normal">
                  Our website is scanned on a regular basis for security holes
                  and known vulnerabilities in order to make your visit to our
                  site as safe as possible. We use regular Malware Scanning to
                  protect our data base. We take reasonable steps including
                  administrative, technical and physical measures to protect
                  Sensitive Personal Data from misuse, lossand from unauthorised
                  access, modification or disclosure. CarLand aim to maintain
                  appropriate physical, procedural and electronic safeguards to
                  protect your personal data and for this purpose we implement
                  internal review system, storage and processing practices and
                  security measures to guard against unauthorized access to
                  systems, where CarLand stores Your Sensitive Personal Data.,
                  provided that client’s right to claim damages shall be limited
                  to the right to claim only statutory damages under Information
                  Technology Act, 2000 and You hereby waive and release CarLand
                  from any claim of damages under contract, tort or any other
                  applicable laws. As you may be aware, there is no completely
                  secure method of transmitting or storing data. Although their
                  physical characteristics are different, postal mail, telephone
                  calls, text messages, faxes and transmissions over the
                  Internet or wireless networks all present possibilities exists
                  for loss, misrouting, interception and misuse of the data that
                  is transmitted. When you use Vroom Drive’s services or post on
                  the Website, some of the Sensitive Personal Data You share is
                  visible to other users and can be read, collected, or used by
                  them. CarLand is not responsible for such Sensitive Personal
                  Data You choose to submit in these instances. For example, if
                  you place your name, email address and telephone number on the
                  Website, that information is public. Further, CarLand is not
                  responsible for maintaining the confidentiality of your
                  account and password and for restricting access to your
                  computer, and you agree to accept responsibility for all
                  activities that occur under your account or password. In spite
                  of anything contained in this Privacy Policy or elsewhere,
                  CarLand shall not be held responsible for any loss, damage or
                  misuse of Your Sensitive Personal Data, if such loss, damage
                  or misuse is attributable to a Force Majeure Event (as defined
                  below). A “Force Majeure Event” shall mean any event that is
                  beyond our reasonable control and shall include, without
                  limitation, sabotage, fire, flood, explosion, acts of God,
                  civil commotion, strikes or industrial action or any kind,
                  riots, insurrection, war, acts of government, computer
                  hacking, unauthorized access to your mobile or storage device,
                  crashes, breach of security and encryption, power failures,
                  industrial disputes affecting any third party, changes to the
                  law, disaster, terrorist attacks and wars. We generally retain
                  personal data about our customers for as long as we believe
                  appropriate for the purposes for which it was collected
                  whereas Non-Sensitive Personal Data will be preserved for an
                  indefinite period.
                </h2>
              </div>
              <div className="flex flex-col gap-2">
                <h2 className="text-xl font-medium">4. Disclaimer:</h2>
                <h2 className="text-base font-normal">
                  Every effort has been made to ensure that the information on
                  this site is correct and up to date, however, CarLand does not
                  provide any warranty as to the completeness or accuracy of the
                  information and, subject to applicable laws, does not accept
                  any liability for damages of any kind resulting from the
                  access or use of this website and its contents. All
                  information on this site is protected by copyright and other
                  intellectual property rights. No images, text or other content
                  from this site may be distributed or reproduced without prior
                  written approval from CarLand.
                  <br />
                  <span className="font-semibold">
                    We do not specifically market to children under the age of
                    18 years old.
                  </span>
                </h2>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Privacy;
