export const cars = [
  {
    carName: "Honda Civic",
    pricePerDay: 1200,
    imgSrc: "/Honda Civic.png",
    numberOfSeat: 5,
    mpg: 28,
  },
  {
    carName: "Mazda CX3",
    pricePerDay: 1500,
    imgSrc: "/Mazda CX3.png",
    numberOfSeat: 5,
    mpg: 35,
  },
  {
    carName: "BMW X3",
    pricePerDay: 3800,
    imgSrc: "/BMW X3.png",
    numberOfSeat: 5,
    mpg: 5,
  },
  {
    carName: "Honda Jazz",
    pricePerDay: 2500,
    imgSrc: "/Honda Jazz.png",
    numberOfSeat: 5,
    mpg: 40,
  },
  {
    carName: "Lexus ES7",
    pricePerDay: 3000,
    imgSrc: "/Lexus ES7.png",
    numberOfSeat: 5,
    mpg: 46,
  },
  {
    carName: "BMW X5",
    pricePerDay: 5000,
    imgSrc: "/BMW X5.png",
    numberOfSeat: 5,
    mpg: 28,
  },
  {
    carName: "Toyota Camry",
    pricePerDay: 2000,
    imgSrc: "/Toyota Camry.png",
    numberOfSeat: 5,
    mpg: 46,
  },
  {
    carName: "Volvo XC 90",
    pricePerDay: 2700,
    imgSrc: "/Volvo XC 90.png",
    numberOfSeat: 7,
    mpg: 33,
  },
  {
    carName: "Tesla S",
    pricePerDay: 3200,
    imgSrc: "/Tesla S.png",
    numberOfSeat: 5,
    mpg: 31,
  },
  {
    carName: "Tesla Y",
    pricePerDay: 3200,
    imgSrc: "/Tesla Y.png",
    numberOfSeat: 7,
    mpg: 40,
  },
];
